import Head from 'next/head'
import '../styles/Home.module.css'
import Header from "../components/Header";
import {useState} from "react";

export default function Home() {
    const firstText = "some text"
    const [someInputValue, setSomeInputValue] = useState(firstText)
    const [pictureText, setPictureText] = useState(firstText)
    return (<div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Header someValue={someInputValue} setSomeValue={setSomeInputValue} setPictureText={setPictureText}/>
                <h1>{someInputValue}</h1>
                {/* deleted sad tag */}
                <img src={`https://cataas.com/cat/says/${pictureText}`} />
            </div>
        </div>)
}