import Head from 'next/head'
import '../styles/Home.module.css'
import Header from "../components/Header";

export default function Home() {
    return (<div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Header/>
            </div>
        </div>)
}